### ISSUE TITLE
Parameter used in example doesn't match response from Typekit server.

### ISSUE THREAD

**Issue by rglover** [bramstein/node-typekit#1]
In the "and then include it in your code example" in the docs, the id parameter used in the create callback is identified as data.id, but the response coming back from the server is nested as data.kit.id. 

Tested both cases, data.id and with data.kit.id, and the latter works without errors.

Example usage (with updated parameter):

```
# Create typekit kit
typekit.create(apiKey, {
  name: 'Pretend: ' + guide.name
  families: [{id: guide.typography.headerFont.id}, {id: guide.typography.bodyFont.id}]
  domains: ['localhost', 'pretendwith.us', 'meteor.com']
}, (error,data) ->

  if error
    console.log "Create Kit Error:"
    console.log error
  else

    # Publish new kit
    typekit.publish(apiKey, data.kit.id, (error) ->
      if error
        console.log "Error with publish:"
        console.log error
    ) #end typekit.publish

    return

) #end typekit.create
```

**Comment by bramstein** [comment]
Thanks, that was a mistake I made when I wrote down the example from memory. It is fixed now, thanks again!

**Comment by rglover** [comment]
That was quick! Cheers :)
